name: chfs_gui
description: A new Flutter project.
publish_to: 'none'
version: 1.1.3

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  file_picker: ^5.2.10
  flutter:
    sdk: flutter
  process_run: ^0.13.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  window_manager: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
